---
version: "2.0"

services:
  ipfs-node:
    image: ipfs/go-ipfs:v0.7.0
    expose:
      - port: 4001
        as: 4001
        to:
          - global: true
      - port: 8080
        as: 8080
        to:
          - global: true
      - port: 5001
        as: 5001
        to:
          - global: true
    env:
      - IPFS_PROFILE=server

profiles:
  compute:
    ipfs-node:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 2Gi
        storage:
          size: 10Gi

  placement:
    dcloud:
      attributes:
        host: akash
      pricing:
        ipfs-node:
          denom: uakt
          amount: 5000

deployment:
  ipfs-node:
    dcloud:
      profile: ipfs-node
      count: 1